#ifndef __DOIPCOMMONN_H__
#define __DOIPCOMMONN_H__

typedef enum {
    RESERVED = 0x00,
    VERSION_2010 = 0x01,
    VERSION_2012 = 0x02,
    DEFAULT_VALUE_FOR_VEHICLE_IDENTIFICATION_REQUEST_MESSAGES = 0xFF
} ProtocolVersion;

typedef enum {
    GENERIC_DoIP_HEADER_NEGATIVE_ACKNOWLEDGE = 0x0000,
    VEHICLE_ANNOUNCEMENT_MESSAGE = 0x0004,
    ROUTING_ACTIVATION_RESPONSE = 0x0006,
    ALIVE_CHECK_REQUEST = 0X0007,
    DoIP_ENTITY_STATUS_RESPONSE = 0x4002,
    DIAGNOSTIC_POWER_MODE_INFORMATION_RESPONSE = 0x4004,
    DIAGNOSTIC_MESSAGE = 0x8001,
    DIAGNOSTIC_MESSAGE_POSITIVE_ACKNOWLEDGEMENT = 0x8002,
    DIAGNOSTIC_MESSAGE_NEGATIVE_ACKNOLWDGEMENT = 0x8003
} DoIPClientPayloadType;


typedef enum {
    GENERIC_DoIP_HEADER_NEGATIVE_ACKNOWLEDGE = 0x0000,
    VEHICLE_IDENTIFICATION_REQUEST_MESSAGE = 0x0001,
    VEHICLE_IDENTIFICATION_REQUEST_MESSAGE_WITH_EID = 0x0002,
    VEHICLE_IDENTIFICATION_REQUEST_MESSAGE_WITH_VIN = 0X0003,
    ROUTING_ACTIVATION_REQUEST = 0x0005,
    ALIVE_CHECK_RESPONSE = 0x0008,
    DoIP_ENTITY_STATUS_REQUEST = 0x4001,
    DIAGNOSTIC_POWER_MODE_INFORMATION_REQUEST = 0x4003,
    DIAGNOSTIC_MESSAGE = 0x8001
} DoIPServerPayloadType;


#endif